export const rewardList = [
  {
    id: 1,
    src: "/assets/icons/feed.svg",
    alt: "can",
    label: "밥 주기",
    width: 54,
    height: 50,
  },
  {
    id: 2,
    src: "/assets/icons/stroke.svg",
    alt: "hand",
    label: "쓰다듬기",
    width: 50,
    height: 50,
  },
  {
    id: 3,
    src: "/assets/icons/play.svg",
    alt: "fishing rod",
    label: "놀아주기",
    width: 50,
    height: 50,
  },
  {
    id: 4,
    src: "/assets/inventory/sunglasses.svg",
    alt: "sunglasses",
    label: "안경",
    width: 50,
    height: 50,
  },
  {
    id: 5,
    src: "/assets/inventory/cap.svg",
    alt: "cap",
    label: "모자",
    width: 50,
    height: 50,
  },
  {
    id: 6,
    src: "/assets/inventory/necklace.svg",
    alt: "necklace",
    label: "목걸이",
    width: 50,
    height: 50,
  },
  {
    id: 7,
    src: "/assets/inventory/bed.svg",
    alt: "bed",
    label: "침대",
    width: 50,
    height: 50,
  },
  {
    id: 8,
    src: "/assets/inventory/tree.svg",
    alt: "tree",
    label: "나무 모형",
    width: 50,
    height: 50,
  },
  {
    id: 9,
    src: "/assets/inventory/catTower.svg",
    alt: "catTower",
    label: "캣타워",
    width: 50,
    height: 50,
  },
];
